[project]
name = "doc-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "black>=25.11.0",
    "certifi>=2026.6.17",
    "isort>=6.1.0",
    "langchain>=0.3.30",
    "langchain-chroma>=0.2.6",
    "langchain-community>=0.3.31",
    "langchain-core>=0.3.86",
    "langchain-openai>=0.3.35",
    "langchain-pinecone>=0.2.12",
    "langchain-tavily>=0.2.11",
    "langchain-text-splitters>=0.3.11",
    "langchainhub>=0.1.21",
    "python-dotenv>=1.2.1",
    "streamlit>=1.50.0",
]
